### ISSUE TITLE
Won't work in Opera

### ISSUE THREAD

**Issue by CrackerHax** [amaurymartiny/login-with-metamask-demo#12]
Just letting you know I can't get your demo to work in opera with metamask installed.

**Comment by amaurymartiny** [comment]
Thanks for the issue! Can you describe the issue, what doesn't work?

- Do you see any error message in the console?
- Which step doesn't work?

Thanks.

**Comment by CrackerHax** [comment]
When clicking the login with metamask button it says metamask is not installed, even though it is and works on other sites.

**Comment by amaurymartiny** [comment]
Correct, reproed.

**Comment by amaurymartiny** [comment]
closed by #172 (not sure if opera version update, or CRA update, or metamask update though...)
