### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by cmayorga** [amaurymartiny/login-with-metamask-demo#161]
I think code in the tutorial is not the same that repository.... i am unable to compile

\login-with-metamask-demo\node_modules\ts-node\src\index.ts:500
[start:backend ]     return new TSError(diagnosticText, diagnosticCodes)
[start:backend ]            ^
[start:backend ] TSError: ⨯ Unable to compile TypeScript:
[start:backend ] src/services/users/controller.ts(12,23): error TS2345: Argument of type '"" | { where: { publicAddress: string | ParsedQs | string[] | ParsedQs[]; }; } | undefined' is not assignable to parameter of type 'FindOptions<any> | undefined'.
[start:backend ]   Type '""' is not assignable to type 'FindOptions<any> | undefined'.

**Comment by amaurymartiny** [comment]
> I think code in the tutorial is not the same that repository

Yes, that's correct. See the "Important Note" in the README.

Would you like to create a PR to fix the compile error (it shouldn't be hard).

**Comment by cmayorga** [comment]
Yep, i noticed the "Important Note" ;)
I meant the current code is unable to start, i can create a PR but no changes from master, simply clone->yarn install->yarn start
and got the error
