### ISSUE TITLE
I am unable to run this

### ISSUE THREAD

**Issue by cmayorga** [amaurymartiny/login-with-metamask-demo#162]
I don't know if i am missing something, i am just following steps from scratch and find myself hours here without success, just clone-> yarn install -> yarn start, and getting this.... any help appreciated please

[start:backend ] (sequelize) Warning: SQLite does not support 'INTEGER' with UNSIGNED or ZEROFILL. Plain 'INTEGER' will be used instead. 
[start:backend ] >> Check: https://www.sqlite.org/datatype3.html
[start:backend ] 
[start:backend ] [mylocalPATH]\login-with-metamask-demo\node_modules\express-jwt\lib\index.js:22
[start:backend ]   if (!options.algorithms) throw new Error('algorithms should be set');

**Comment by amaurymartiny** [comment]
Correct, I just fixed it. Dockerfile still doesn't work (i'm not 100% sure why, see #174), but running with yarn should work now: https://github.com/amaurymartiny/login-with-metamask-demo#start-the-demo-using-yarn
