### ISSUE TITLE
package express-jwt now requires algorithms explicitly set.

### ISSUE THREAD

**Issue by edugrip** [amaurymartiny/login-with-metamask-demo#171]
However if we set algorithms : ['RS256'], and then provide the `options` parameter in the jwt.sign method, It generates some line start error. 
Please test if this code works.

**Comment by amaurymartiny** [comment]
Correct, I just fixed it. Dockerfile still doesn't work (i'm not 100% sure why, see #174), but running with yarn should work now: https://github.com/amaurymartiny/login-with-metamask-demo#start-the-demo-using-yarn
