### ISSUE TITLE
`TypeError: Failed to fetch` when trying to login with MetaMask

### ISSUE THREAD

**Issue by ppseprus** [amaurymartiny/login-with-metamask-demo#44]
**Steps to reproduce**:
1. Try to login with MetaMask
2. Click "Connect" on the MetaMask confirmation page

**Expected Outcome**: To login

**Actual Outcome**: `TypeError: Failed to fetch`

**Comment by amaurymartiny** [comment]
Sorry about that, it should be fixed now.

**Comment by ppseprus** [comment]
Ah! Perfect! Thanks!
Great repo btw!

**Comment by valbtw** [comment]
Hi, I'm having the same Issue while using the master branch. Any Idea where that could come from?
Thanks in advance :)
