### ISSUE TITLE
Installing in cpanel

### ISSUE THREAD

**Issue by corpoeureka** [amaurymartiny/login-with-metamask-demo#9]
Hi, how can I install this app on a cpanel server

**Comment by amaurymartiny** [comment]
The steps would be:

- install nodejs on your cpanel server, see for example https://stackoverflow.com/questions/44079039/run-node-js-on-cpanel-hosting-server
- Clone the db on your server, and run the backend https://github.com/amaurymartiny/login-with-metamask-demo#start-the-backend-using-yarn

I don't have much experience with cpanel. Will close this issue for now, as it's not related to the codebase itself.
